const fakeResponse = {
  products: [
    {
      id: 1,
      title: "Essence Mascara Lash Princess",
      description:
        "The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.",
      category: "beauty",
      price: 9.99,
      discountPercentage: 7.17,
      rating: 4.94,
      stock: 5,
      tags: ["beauty", "mascara"],
      brand: "Essence",
      sku: "RCH45Q1A",
      weight: 2,
      dimensions: {
        width: 23.17,
        height: 14.43,
        depth: 28.01,
      },
      warrantyInformation: "1 month warranty",
      shippingInformation: "Ships in 1 month",
      availabilityStatus: "Low Stock",
      reviews: [
        {
          rating: 2,
          comment: "Very unhappy with my purchase!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "John Doe",
          reviewerEmail: "john.doe@x.dummyjson.com",
        },
        {
          rating: 2,
          comment: "Not as described!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "Nolan Gonzalez",
          reviewerEmail: "nolan.gonzalez@x.dummyjson.com",
        },
        {
          rating: 5,
          comment: "Very satisfied!",
          date: "2024-05-23T08:56:21.618Z",
          reviewerName: "Scarlett Wright",
          reviewerEmail: "scarlett.wright@x.dummyjson.com",
        },
      ],
      returnPolicy: "30 days return policy",
      minimumOrderQuantity: 24,
      meta: {
        createdAt: "2024-05-23T08:56:21.618Z",
        updatedAt: "2024-05-23T08:56:21.618Z",
        barcode: "9164035109868",
        qrCode: "...",
      },
      thumbnail: "...",
      images: ["...", "...", "..."],
    },
    {
      id: 2,
      title: "Maybelline Super Stay Foundation",
      description:
        "Long-lasting foundation with full coverage and matte finish. Transfer-resistant formula that lasts up to 24 hours.",
      category: "beauty",
      price: 14.99,
      discountPercentage: 10.5,
      rating: 4.7,
      stock: 32,
      tags: ["beauty", "makeup", "foundation"],
      brand: "Maybelline",
      sku: "MSF2024B",
      weight: 3,
      dimensions: {
        width: 15.5,
        height: 8.2,
        depth: 12.8,
      },
      warrantyInformation: "No warranty",
      shippingInformation: "Ships in 2 business days",
      availabilityStatus: "In Stock",
      reviews: [
        {
          rating: 5,
          comment: "Perfect coverage for my skin!",
          date: "2024-06-10T10:30:00.000Z",
          reviewerName: "Emma Johnson",
          reviewerEmail: "emma.johnson@x.dummyjson.com",
        },
        {
          rating: 4,
          comment: "Good product but slightly drying",
          date: "2024-06-08T14:20:00.000Z",
          reviewerName: "Michael Chen",
          reviewerEmail: "michael.chen@x.dummyjson.com",
        },
      ],
      returnPolicy: "60 days return policy",
      minimumOrderQuantity: 1,
      meta: {
        createdAt: "2024-05-15T09:12:45.123Z",
        updatedAt: "2024-06-01T11:20:30.456Z",
        barcode: "7452896310475",
        qrCode: "...",
      },
      thumbnail: "...",
      images: ["...", "...", "..."],
    },
    {
      id: 3,
      title: "Samsung Galaxy S24 Ultra",
      description:
        "Flagship smartphone with advanced AI features, 200MP camera, and S Pen integration. Powered by Snapdragon 8 Gen 3 processor.",
      category: "electronics",
      price: 1299.99,
      discountPercentage: 15.25,
      rating: 4.8,
      stock: 18,
      tags: ["electronics", "smartphone", "samsung"],
      brand: "Samsung",
      sku: "SGS24U512",
      weight: 232,
      dimensions: {
        width: 78.1,
        height: 162.3,
        depth: 8.6,
      },
      warrantyInformation: "2 years warranty",
      shippingInformation: "Ships in 1-2 business days",
      availabilityStatus: "In Stock",
      reviews: [
        {
          rating: 5,
          comment: "Best phone I've ever owned!",
          date: "2024-06-12T16:45:22.789Z",
          reviewerName: "Alex Rodriguez",
          reviewerEmail: "alex.rodriguez@x.dummyjson.com",
        },
        {
          rating: 4,
          comment: "Excellent but quite expensive",
          date: "2024-06-05T12:10:15.333Z",
          reviewerName: "Sarah Miller",
          reviewerEmail: "sarah.miller@x.dummyjson.com",
        },
      ],
      returnPolicy: "30 days return policy",
      minimumOrderQuantity: 1,
      meta: {
        createdAt: "2024-04-20T07:30:10.555Z",
        updatedAt: "2024-06-10T13:45:20.111Z",
        barcode: "8806092765432",
        qrCode: "...",
      },
      thumbnail: "...",
      images: ["...", "...", "..."],
    },
    {
      id: 4,
      title: "Nike Air Max 270",
      description:
        "Comfortable lifestyle shoes with Max Air cushioning for all-day comfort. Features breathable mesh upper and rubber outsole.",
      category: "fashion",
      price: 159.99,
      discountPercentage: 20.0,
      rating: 4.6,
      stock: 45,
      tags: ["fashion", "shoes", "sneakers", "nike"],
      brand: "Nike",
      sku: "NIKEAM270B",
      weight: 350,
      dimensions: {
        width: 25,
        height: 15,
        depth: 35,
      },
      warrantyInformation: "6 months warranty",
      shippingInformation: "Ships in 3-5 business days",
      availabilityStatus: "In Stock",
      reviews: [
        {
          rating: 5,
          comment: "Extremely comfortable for walking",
          date: "2024-05-28T09:15:42.987Z",
          reviewerName: "David Wilson",
          reviewerEmail: "david.wilson@x.dummyjson.com",
        },
        {
          rating: 3,
          comment: "Size runs small, order half size up",
          date: "2024-05-20T18:30:10.222Z",
          reviewerName: "Lisa Taylor",
          reviewerEmail: "lisa.taylor@x.dummyjson.com",
        },
      ],
      returnPolicy: "90 days return policy",
      minimumOrderQuantity: 1,
      meta: {
        createdAt: "2024-03-10T10:00:00.000Z",
        updatedAt: "2024-05-25T14:22:33.444Z",
        barcode: "8852597123456",
        qrCode: "...",
      },
      thumbnail: "...",
      images: ["...", "...", "..."],
    },
    {
      id: 5,
      title: "Instant Pot Duo 7-in-1",
      description:
        "7-in-1 multi-functional pressure cooker that replaces 7 kitchen appliances. Features 14 safety mechanisms and easy-to-use controls.",
      category: "home",
      price: 89.99,
      discountPercentage: 25.0,
      rating: 4.9,
      stock: 22,
      tags: ["home", "kitchen", "appliance", "cooking"],
      brand: "Instant Pot",
      sku: "IPDUO6QT",
      weight: 5200,
      dimensions: {
        width: 33,
        height: 33,
        depth: 30,
      },
      warrantyInformation: "1 year warranty",
      shippingInformation: "Ships in 1 week",
      availabilityStatus: "In Stock",
      reviews: [
        {
          rating: 5,
          comment: "Revolutionized my cooking!",
          date: "2024-06-03T11:45:12.666Z",
          reviewerName: "Robert Brown",
          reviewerEmail: "robert.brown@x.dummyjson.com",
        },
        {
          rating: 5,
          comment: "Saves so much time in the kitchen",
          date: "2024-05-30T20:15:40.123Z",
          reviewerName: "Jennifer Lee",
          reviewerEmail: "jennifer.lee@x.dummyjson.com",
        },
        {
          rating: 4,
          comment: "Great product, manual could be better",
          date: "2024-05-25T13:22:18.999Z",
          reviewerName: "Thomas Anderson",
          reviewerEmail: "thomas.anderson@x.dummyjson.com",
        },
      ],
      returnPolicy: "30 days return policy",
      minimumOrderQuantity: 1,
      meta: {
        createdAt: "2024-04-05T08:45:30.777Z",
        updatedAt: "2024-06-08T16:10:25.888Z",
        barcode: "6921446789012",
        qrCode: "...",
      },
      thumbnail: "...",
      images: ["...", "...", "..."],
    },
  ],
  total: 194,
  skip: 0,
  limit: 30,
};
